# Generated by Django 3.2.19 on 2025-04-27 02:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='products',
            name='product_category',
            field=models.CharField(max_length=30),
        ),
        migrations.AlterField(
            model_name='products',
            name='product_description',
            field=models.TextField(null=True),
        ),
    ]
